version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@salesforce/ui-bundle-template-app-react-sample-b2e"
      - dependency-name: "@salesforce/ui-bundle-template-app-react-sample-b2x"
      - dependency-name: "@salesforce/webapp-template-app-react-sample-b2e-experimental"
      - dependency-name: "@salesforce/webapp-template-app-react-sample-b2x-experimental"
      - dependency-name: "fast-uri"
      - dependency-name: "axios"

  - package-ecosystem: "npm"
    directory: "/samples/ui-bundle-template-app-react-sample-b2e"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/samples/ui-bundle-template-app-react-sample-b2x"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/samples/webapp-template-app-react-sample-b2e-experimental"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/samples/webapp-template-app-react-sample-b2x-experimental"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/samples/native-mobile-rental-tenant-app"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/samples/ui-bundle-template-app-react-sample-b2x/force-app/main/default/uiBundles/propertyrentalapp"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/samples/ui-bundle-template-app-react-sample-b2e/force-app/main/default/uiBundles/propertymanagementapp"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
