version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@salesforce/ui-bundle-template-app-react-sample-b2e"
      - dependency-name: "@salesforce/ui-bundle-template-app-react-sample-b2x"
      - dependency-name: "@salesforce/webapp-template-app-react-sample-b2e-experimental"
      - dependency-name: "@salesforce/webapp-template-app-react-sample-b2x-experimental"
